
delete from configuration_rubrique_budgetaire_generale;
select * from configuration_rubrique_budgetaire_generale;

INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (1,0,'61','Charges d''exploitations','Depenses', 1,null);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (2,0,'612','Achat de consomes de matières et fournitures','Depenses', 1,1);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (3,0,'6122','Achats de matières et fournitures consommables','Depenses', 1,2);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (4,0,'61222','Achat de vignettes de carburant','Depenses', 1,3);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (5,0,'61224','Achat de produits d''entretien','Depenses', 1,3);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (6,0,'61227','Achats de fournitures de bureau','Depenses', 1,3);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (7,0,'61228','Achats de fournitures pour le matériel informatique','Depenses', 1,3);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (8,0,'6125','Achats non stockés de matières et de fournitures','Depenses', 1,2);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (9,0,'61251','Achats de fournitures non stockables','Depenses', 1,8);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (10,0,'612511','Redevances d''Eau','Depenses', 1,9);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (11,0,'612512','Redevances d''Electricité','Depenses', 1,9);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (12,0,'6126','Achats de travaux, études et prestations de service','Depenses', 1,2);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (13,0,'61263','Achats des prestations de service','Depenses', 1,12);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (14,0,'612631','Impression des documents','Depenses', 1,13);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (15,0,'612632','Frais de formation et stage                                                          ','Depenses', 1,13);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (16,0,'612633','Frais de cours et vacations','Depenses', 1,13);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (17,0,'612635','Frais de correction des examens et concours','Depenses', 1,13);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (18,0,'612636','Gardiennage et acceuil','Depenses', 1,13);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (19,0,'612637','Jardinage','Depenses', 1,13);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (20,0,'612638','Edition des CD institutionnelles et du monographie de la région','Depenses', 1,13);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (21,0,'612639','Nettoyage des biens immobiliers (bâtiments administratifs)','Depenses', 1,13);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (22,0,'6126310','Edition de rapports d''activité, de revues institutionnelles et de bulletin d''information','Depenses', 1,13);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (23,0,'6126311','Edition et création des objets de communication et de publicité','Depenses', 1,13);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (24,0,'6126312','frais de tansport de messagerie et de colis','Depenses', 1,13);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (25,0,'613/614','Autres charges externes','Depenses', 1,1);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (26,0,'6131','Locations et charges locatives','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (27,0,'61312','Location de constructions (bâtiments administratifs)','Depenses', 1,26);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (28,0,'61313','Location de matériel et d''outillage','Depenses', 1,26);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (29,0,'61316','Location de matériel de transport','Depenses', 1,26);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (30,0,'6133','Entretien et Réparations','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (31,0,'61331','Entretien et réparation des biens immobiliers (bâtiments administratifs)','Depenses', 1,30);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (33,0,'61332','Entretien et réparation des biens mobiliers','Depenses', 1,30);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (34,0,'613321','Entretien et réparation de mobilier et du matériel du bureau','Depenses', 1,33);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (35,0,'613322','Entretien et réparation du matériel informatique','Depenses', 1,33);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (36,0,'613323','Entretien et réparation de véhicules','Depenses', 1,33);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (37,0,'61335','Maintenance (matériel technique, informatique)','Depenses', 1,30);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (38,0,'613351','Contrat de maintenance du matériel technique et informatique','Depenses', 1,37);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (39,0,'6134','Primes d''assurances','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (40,0,'61341','Assurance multirisques','Depenses', 1,39);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (41,0,'613411','Assurance accidents de travail pour le personnel','Depenses', 1,40);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (42,0,'613412','Assurance individuelle contre les accidents corporels pour les membres','Depenses', 1,40);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (43,0,'613413','Responsabilité civile','Depenses', 1,40);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (44,0,'613414','Assurance incendie (locaux administratifs)','Depenses', 1,40);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (45,0,'61345','Assurance matériel de transport ','Depenses', 1,39);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (46,0,'613451','Assurance véhicule','Depenses', 1,45);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (47,0,'6135','Rémunération du personnel extérieur à l''établissement','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (48,0,'61352','Rémunération du personnel détaché à la CCIS','Depenses', 1,47);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (49,0,'613521','Administrateur','Depenses', 1,48);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (50,0,'613522','Ingénieur d''Etat','Depenses', 1,48);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (51,0,'6136','Rémunérations d''intermédiaires et honoraires','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (52,0,'61365','Honoraires','Depenses', 1,51);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (53,0,'613651','Honoraires d''avocats','Depenses', 1,52);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (54,0,'613652','Honoraires de juris-consultes et d''experts','Depenses', 1,52);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (55,0,'61367','Frais d''actes et de contentieux (Règlement et exécution des décisions judiciaires et administratives)','Depenses', 1,51);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (56,0,'6141','Etudes, recherches et documents','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (57,0,'61411','Etudes générales (études économiques)','Depenses', 1,56);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (58,0,'61412','Etudes monographiques','Depenses', 1,56);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (59,0,'61413','Etudes sur les zones d''activités économiques','Depenses', 1,56);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (60,0,'61414','Crédits non programmés','Depenses', 1,56);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (61,0,'61415','Assistancetechniquepour mise en œuvre du plan de développement de la CCIS FM','Depenses', 1,56);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (62,0,'61415','Documentation générale','Depenses', 1,56);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (63,0,'61416','Audit ','Depenses', 1,56);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (64,0,'61419','Abonnement aux revues et journaux','Depenses', 1,56);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (65,0,'6142','Transports','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (66,0,'61421','Transports du personnel et des membres','Depenses', 1,65);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (67,0,'614211','Frais du transport des membres à l''intérieur du Maroc','Depenses', 1,66);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (68,0,'614212','Frais du transport des membres à l''étranger','Depenses', 1,66);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (69,0,'614213','Frais du transport du personnel à l''intérieur du Maroc','Depenses', 1,66);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (70,0,'614214','Frais du transport du personnel à l''étranger','Depenses', 1,66);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (71,0,'614215','Indemnités kilométriques','Depenses', 1,66);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (72,0,'614216','Abonnement cartes d''autoroutes du Maroc','Depenses', 1,66);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (73,0,'6143','Déplacements, missions et réceptions','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (74,0,'61431','Voyages et déplacements','Depenses', 1,73);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (75,0,'614311','Indemnités de déplacement des membres à l''intérieur du Maroc','Depenses', 1,74);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (76,0,'614312','Indemnités de déplacement du personnel à l''intérieur du Maroc','Depenses', 1,74);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (77,0,'614313','Indemnités de déplacement des enquêteurs','Depenses', 1,74);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (78,0,'61435','Missions','Depenses', 1,73);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (79,0,'614351','Indemnités de mission des membres à l''étranger','Depenses', 1,78);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (80,0,'614352','Indemnités de mission du personnel à l''étranger','Depenses', 1,78);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (81,0,'61436','Réceptions','Depenses', 1,73);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (82,0,'614361','Frais de réceptions','Depenses', 1,81);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (83,0,'614362','Frais d''hébergement','Depenses', 1,81);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (84,0,'614363','Frais de restauration','Depenses', 1,81);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (85,0,'6144','Publicité, publications et relations publiques','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (86,0,'61441','Annonces et insertions ','Depenses', 1,85);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (87,0,'61443','Participation aux Foires et Expositions','Depenses', 1,85);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (88,0,'614431','Déplacement des participants','Depenses', 1,87);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (89,0,'614432','Aménagement de stand et de salles d''exposition','Depenses', 1,87);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (90,0,'614433','Location de stands','Depenses', 1,87);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (91,0,'614434','Location de matériel','Depenses', 1,87);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (92,0,'61446','Publications','Depenses', 1,85);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (94,0,'61448','Autres charges de publicité et relations publiques','Depenses', 1,85);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (95,0,'614481','Organisation ou Participation aux Séminaires et Conférences','Depenses', 1,94);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (96,0,'6144811','Frais de consultants et de conférenciers','Depenses', 1,95);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (97,0,'6144812','Frais de participation','Depenses', 1,95);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (98,0,'6144813','Location de salles de conférences','Depenses', 1,95);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (99,0,'6144814','Location de matériel','Depenses', 1,95);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (100,0,'6144815','Frais de réception','Depenses', 1,95);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (101,0,'6144816','Restauration','Depenses', 1,95);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (103,0,'6145','Frais postaux et frais de télécommunications  ','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (104,0,'61451','Frais postaux','Depenses', 1,103);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (105,0,'614511','Taxes postales et frais d''affranchissement','Depenses', 1,104);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (106,0,'61455','Frais de téléphone','Depenses', 1,103);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (107,0,'614551','Taxes et redevances de télécommunication','Depenses', 1,106);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (108,0,'61457','Frais d''abonnement à l''internet','Depenses', 1,103);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (109,0,'61458','Taxes et redevances pour utilisation de lignes ou de réseaux spécialisés','Depenses', 1,103);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (110,0,'6146','Cotisations et dons','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (111,0,'61461','Cotisations aux organismes internationaux (Adhésion à ASCAME , CPCCAF….)','Depenses', 1,110);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (112,0,'6147','Agios et frais de compte','Depenses', 1,25);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (113,0,'614811','Contribution accordée à la fondation forum économique de la Région Fès -Meknès','Depenses', 1,null);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (114,0,'6151','Organisation du meditour 2020','Depenses', 1,1);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (115,0,'61511','Location des salles de conférence','Depenses', 1,114);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (116,0,'61512','Assistance à l''Organisation, Communication et interprête','Depenses', 1,114);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (117,0,'61513','Agencement et aménagement de stands','Depenses', 1,114);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (118,0,'61514','Location du matériel de transport','Depenses', 1,114);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (119,0,'61515','Frais de réception','Depenses', 1,114);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (120,0,'61516','Restauration','Depenses', 1,114);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (121,0,'61517','Hébergement','Depenses', 1,114);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (122,0,'61518','Impression de documents ','Depenses', 1,114);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (123,0,'61519','Edition de reportage, de Vidéo et de films','Depenses', 1,114);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (124,0,'615110','Location du matériel technique, audio-visuel ','Depenses', 1,115);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (125,0,'616','Impots et taxes','Depenses', 1,1);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (126,0,'6161','Impôts et Taxes directs','Depenses', 1,125);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (127,0,'61611','Taxe urbaine','Depenses', 1,126);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (128,0,'6167','Impôts, Taxes et droits assimilés','Depenses', 1,125);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (129,0,'61671','Droit d''enregistrement et timbres','Depenses', 1,128);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (130,0,'61673','Taxes sur les véhicules','Depenses', 1,128);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (131,0,'617','Charges du personnel ','Depenses', 1,1);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (132,0,'6171','Rémunérations du personnel ','Depenses', 1,131);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (133,0,'61711','Appointements et salaires','Depenses', 1,132);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (134,0,'617111','Personnel titulaire','Depenses', 1,133);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (135,0,'617112','Personnel contractuel','Depenses', 1,133);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (136,0,'617113','Personnel temporaire','Depenses', 1,133);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (137,0,'617114','Personnel non permanent (occasionnel)','Depenses', 1,133);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (138,0,'61712','Primes et gratifications','Depenses', 1,132);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (139,0,'617121','Prime de productivité','Depenses', 1,138);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (140,0,'61713','Indemnités et avantages divers :','Depenses', 1,132);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (141,0,'617131','Indemnités de logement','Depenses', 1,140);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (142,0,'617132','Indemnités de transport','Depenses', 1,140);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (143,0,'617133','Indemnités de fonction','Depenses', 1,140);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (144,0,'617134','Indemnités de caisse','Depenses', 1,140);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (145,0,'617135','Indemnités forfaitaires pour utilisation dans l''intérêt du service de voiture automobile personnelle','Depenses', 1,140);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (146,0,'617136','Indemnité de représentation','Depenses', 1,140);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (147,0,'617137','Indemnités horaires pour travaux supplémentaires','Depenses', 1,140);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (148,0,'617138','Indemnités à l''agent comptable','Depenses', 1,140);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (149,0,'6174','Charges sociales','Depenses', 1,131);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (150,0,'61742','Cotisations aux caisses de retraite (CMR, RCAR)','Depenses', 1,149);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (151,0,'617421','Cotisations patronales au titre de la Caisse Marocaine de Retraites (CMR)','Depenses', 1,150);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (152,0,'617422','Cotisations patronales au Régime Collectif d''Allocation de Retraites (RCAR)','Depenses', 1,150);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (153,0,'61743','Cotisations aux mutuelles','Depenses', 1,149);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (154,0,'61744','Prestations familiales','Depenses', 1,149);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (155,0,'617441','Allocations et primes de naissance','Depenses', 1,154);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (156,0,'617442','Allocation spéciale en cas de décès','Depenses', 1,154);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (157,0,'6176','Charges sociales diverses','Depenses', 1,131);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (158,0,'61763','Allocations aux œuvres sociales','Depenses', 1,157);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (159,0,'617631','Subvention à l''association d''œuvres sociales du personnel administratif','Depenses', 1,158);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (160,0,'61764','Habillement et vêtements de travail','Depenses', 1,157);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (161,0,'61765','Indémnité de préavis et de licenciement aux agents contractuels','Depenses', 1,157);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (162,0,'61766','Indemnité pour départs volontaires','Depenses', 1,157);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (163,0,'6178','Charges du personnel des exercices antérieurs','Depenses', 1,131);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (164,0,'61781','Rappels sur salaires','Depenses', 1,163);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (165,0,'61782','Promotions','Depenses', 1,163);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (166,0,'618','Autres charges d''exploitation','Depenses', 1,1);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (167,0,'6188','Autres charges d''exploitation des exercices antérieurs (Reste à Payer)','Depenses', 1,166);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (168,0,'6189','Arriérés','Depenses', 1,166);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (169,0,'63','Charges financières','Depenses', 1,1);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (170,0,'631','Charges d''intérêts','Depenses', 1,169);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (171,0,'6311','Intérêts des emprunts et dettes','Depenses', 1,170);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (172,0,'63111','Intérêts des emprunts','Depenses', 1,171);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (173,0,'63115','Intérêts bancaires et sur opérations de financement','Depenses', 1,171);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (174,0,'65','Charges non courants','Depenses', 1,1);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (175,0,'656','Subventions accordées','Depenses', 1,174);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (176,0,'6561','Subventions accordées de l''exercice','Depenses', 1,175);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (177,0,'65611','subvention au centre de gestion de comptabilité agréé','Depenses', 1,176);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (178,0,'65612','subvention au centre de médiation et d''arbitrage','Depenses', 1,176);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (179,0,'65711','Contribution pour la réalisation du shéma directeur du commerce de la ville de taza','Depenses', 1,null);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (180,0,'65712','Contribution de la CCIS FM au covid 19','Depenses', 1,null);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (181,0,'35713','Contribution de la CCIS FM au Fond régional d''apui aux industriels','Depenses', 1,null);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (182,0,'66','Charge du centre Multiservices d''Ain Chkef','Depenses', 1,1);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (183,0,'661','Frais d''installation et redevances d''eau et d''électricité de l''administration ','Depenses', 1,182);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (184,0,'662','Gardiennage et ménage','Depenses', 1,182);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (185,0,'663','Taxes et redevances de télécommunication (Téléphone et Internet)','Depenses', 1,182);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (186,0,'664','Achats de fournitures de bureau','Depenses', 1,182);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (187,0,'665','Achats de fournitures pour le matériel informatique','Depenses', 1,182);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (188,0,'666','Assurance multirisques','Depenses', 1,182);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (189,0,'667','entretien et réparation du bâtiment administratif du centre','Depenses', 1,182);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (190,0,'668','Impression des documents','Depenses', 1,182);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (191,0,'669','Autres charges d''exploitation des exercices antérieurs (Reste à Payer)','Depenses', 1,182);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (192,0,'670','Arriérés','Depenses', 1,182);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (193,0,'671','IS sur Intérêts (Compte Ain Chkef)','Depenses', 1,182);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (194,0,'2','Empois d''investissement','Depenses', 1,1);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (195,0,'21','Immobilisations en non-valeurs','Depenses', 1,194);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (196,0,'211','Frais préliminaires','Depenses', 1,195);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (197,0,'2112','Frais préalables au démarrage','Depenses', 1,196);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (198,0,'23','Immobilisations corporelles','Depenses', 1,194);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (199,0,'231','Terrains','Depenses', 1,198);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (200,0,'2311','Terrains nus','Depenses', 1,199);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (201,0,'2312','Agencements et aménagement de terrains','Depenses', 1,199);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (202,0,'2313','Frais d''acquisition','Depenses', 1,199);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (203,0,'2314','Etudes et contrôle','Depenses', 1,199);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (204,0,'232','Constructions','Depenses', 1,198);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (205,0,'2321','Bâtiments','Depenses', 1,204);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (206,0,'23211','Bâtiments administratifs et commerciaux','Depenses', 1,205);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (207,0,'232111','Honoraires d''architectes','Depenses', 1,206);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (208,0,'2314','Etudes et contrôle','Depenses', 1,199);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (209,0,'232113','Construction de bâtiments administratifs','Depenses', 1,206);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (210,0,'23212','Agencements et aménagements des constructions','Depenses', 1,205);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (211,0,'232121','Agencements et aménagements de bâtiments administratifs','Depenses', 1,210);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (212,0,'232122','Fourniture et pose d''une bâche pour chapiteau','Depenses', 1,210);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (213,0,'23273','Fourniture et pose d''une structutre en alluminium','Depenses', 1,null);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (214,0,'23274','Sol en paquet de bois pour chapiteau','Depenses', 1,null);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (215,0,'232122','Travaux d''aménagement et de réhabitation de bâtiment à Taza','Depenses', 1,201);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (216,0,'232123','Crédits non programmés','Depenses', 1,210);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (217,0,'233','Matériel de transport','Depenses', 1,198);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (218,0,'2331','Achat de véhicule utilitaire (1)','Depenses', 1,217);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (219,0,'2332','Achat de motocycles et cycles','Depenses', 1,217);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (220,0,'2333','Crédits non programmés','Depenses', 1,217);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (221,0,'2341','Mobilier, matériel de bureau et aménagement divers','Depenses', 1,198);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (222,0,'23411','Achat de mobilier de bureau','Depenses', 1,221);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (223,0,'23412','Achat de matériel de bureau','Depenses', 1,221);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (224,0,'23413','Achat de climatiseurs','Depenses', 1,221);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (225,0,'2342','Matériel Informatique','Depenses', 1,198);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (226,0,'23421','Achat de matériel informatique','Depenses', 1,225);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (227,0,'23422','Achat de logiciels','Depenses', 1,225);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (228,0,'23423','Refonte du Portail internet de la CCIS FES','Depenses', 1,225);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (229,0,'2343','Autres mobilier, matériel de bureau et aménagement divers','Depenses', 1,198);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (230,0,'23431','Achat et installation de matériel de télécommunication','Depenses', 1,229);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (231,0,'23432','Achat de matériel pédagogique et audiovisuel','Depenses', 1,229);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (232,0,'235','Immobilisations financières','Depenses', 1,198);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (233,0,'2351','Titres de participation','Depenses', 1,232);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (234,0,'23511','Participation et contribution aux projets d''intérêt économiques','Depenses', 1,233);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (235,0,'235111','Participation au centre de médiation et d''arbitrage','Depenses', 1,234);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (236,0,'235112','Réalisation de la cartographie économique(2)','Depenses', 1,234);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (237,0,'235113','Participation à la fondation agro olivier Meknès','Depenses', 1,234);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (238,0,'235114','Projet de création d''un centre multiservices à la zone industrielle de Taza','Depenses', 1,234);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (239,0,'235115','Réalisation d''une plate forme commerce pour la région','Depenses', 1,234);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (240,0,'235116','Contribution à la réalisation de la zone industrielle Ouislane à Meknes','Depenses', 1,234);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (241,0,'235117','Contribution à la réalisation du parc des expositions de Fès','Depenses', 1,234);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (242,0,'235118','Contribution à la réalisation du palais de la foire à Taza','Depenses', 1,234);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (243,0,'235119','Contribution à la mise à niveau de la ZI Sidi Bouzekri à Meknes ','Depenses', 1,234);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (244,0,'236','Charges d''investissement afférentes à la réationdu CECOGEC','Depenses', 1,198);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (245,0,'2361','création','Depenses', 1,244);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (246,0,'2362','Crédits non programmés','Depenses', 1,244);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (247,0,'237','Charges d''investissement afférentes à la réation du centre d''arbitrage','Depenses', 1,198);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (248,0,'2371','création','Depenses', 1,247);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (249,0,'2372','Crédits non programmés','Depenses', 1,247);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (250,0,'24','Charges d''investissement afférentes au projet de construction d''un parc d''exposition ','Depenses', 1,194);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (251,0,'241','Agencements et aménagements des constructions du parc d''exposition de Fès','Depenses', 1,250);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (252,0,'2411','Honoraires d''architectes','Depenses', 1,251);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (253,0,'2412','Etudes et contrôle','Depenses', 1,251);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (254,0,'2413','Agencements et aménagements de construction du parc d''exposition de Fès','Depenses', 1,251);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (255,0,'2414','Impots, Taxes et droits assimilés','Depenses', 1,251);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (256,0,'2415','Construction et aménagement de batiments','Depenses', 1,251);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (257,0,'2416','Aqcquisition des équipements','Depenses', 1,251);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (258,0,'24','Charges d''investissement afférentes au projet de construction dde la Foire de Taza','Depenses', 1,194);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (259,0,'2421','Honoraires d''architectes','Depenses', 1,258);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (260,0,'2422','Etudes et contrôle','Depenses', 1,258);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (261,0,'2423','Aménagements et construction du Palais de la Foire de Taza','Depenses', 1,258);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (262,0,'2424','Impots, Taxes et droits assimilés','Depenses', 1,258);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (263,0,'24','Charges d''investissement afférentes au projet de la réhabilitation de la zone industrielle de Bensouda Fès','Depenses', 1,194);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (264,0,'2431','Etudes et contrôle','Depenses', 1,263);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (265,0,'2432','Travaux de  réhabilitation (éclairage public – voiries – abords des trottoirs)','Depenses', 1,263);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (266,0,'24','Charges d''investissement afférentes au projet de réalisation d''une zone industrielle dédiée à l''industrie de la chaussure','Depenses', 1,194);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (267,0,'2441','Etudes ','Depenses', 1,266);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (268,0,'23','Charges d''investissement afférentes au projet de la réhabilitation et de valorisation de Kissariat al Kifah Fès - Médina','Depenses', 1,194);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (269,0,'23277','Etudes et contrôle','Depenses', 1,null);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (271,0,'24','Charges d''investissement afférentes au projet de création d''une école de formation à Meknès','Depenses', 1,194);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (272,0,'2461','Etudes','Depenses', 1,271);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (273,0,'2462','Honoraires d''architectes','Depenses', 1,271);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (274,0,'2463','Construction de batiment','Depenses', 1,271);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (275,0,'2464','Aquisition d''un lot de terrain','Depenses', 1,271);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (276,0,'2465','Frais d''acquisition','Depenses', 1,271);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (277,0,'2466','Crédits non programmés','Depenses', 1,271);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (278,0,'24','Charges d''investissement afférentes au projet de création d''un centre multiservices à Missour','Depenses', 1,194);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (279,0,'2471','Honoraires d''architectes','Depenses', 1,278);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (280,0,'2472','Construction de batiment','Depenses', 1,278);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (281,0,'2473','Aquisition d''un lot de terrain','Depenses', 1,278);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (282,0,'2474','Frais d''acquisition','Depenses', 1,278);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (283,0,'2475','Crédits non programmés','Depenses', 1,278);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (284,0,'25','Charge d''investissement du centre Multiservices d''Ain Chkef','Depenses', 1,194);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (285,0,'251','Achat de materiel informatique','Depenses', 1,284);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (286,0,'252','Achat de materiel de bureau','Depenses', 1,284);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (287,0,'253','Achat de mobilier de bureau','Depenses', 1,284);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (288,0,'254','Achat et installation de climatiseurs','Depenses', 1,284);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (289,0,'26','Mise en œuvre du plan de développement','Depenses', 1,194);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (290,0,'261','Achat de matériel et services','Depenses', 1,289);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (291,0,'2611','Acquisition d’infrastructures informatiques de base et réseaux','Depenses', 1,290);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (292,0,'2612','Acquisition et implémentation de solutions informatiques: comptabilité, achats, paie, stocks, immobilisations','Depenses', 1,290);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (293,0,'2613','Initialisation et reconstitution de la comptabilité générale','Depenses', 1,290);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (294,0,'2614','Implémentation de la démarche qualité et de la certification','Depenses', 1,290);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (295,0,'2615','Communication à l''échelle régionale','Depenses', 1,290);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (296,0,'262','Etudes et Assistance Technique','Depenses', 1,289);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (297,0,'263','Projets d''intérêt économique','Depenses', 1,289);
INSERT INTO configuration_rubrique_budgetaire_generale(id, version, code_budg, name, type, created_by,parent)VALUES (298,0,'2631','Crédits non programmés (projet d''intérêt économique)','Depenses', 1,297);

--*************************************************************************************************************************
INSERT INTO public.configuration_rubrique_budgetaire_generale (id, archived, import_id, import_origin, version, created_on, updated_on, attrs, code_budg, name, type, created_by, updated_by, parent) VALUES (301, null, null, null, null, null, null, null, '71', 'Ventes de biens et services produits', 'Recettes', null, null, null);
INSERT INTO public.configuration_rubrique_budgetaire_generale (id, archived, import_id, import_origin, version, created_on, updated_on, attrs, code_budg, name, type, created_by, updated_by, parent) VALUES (302, null, null, null, null, null, null, null, '712', 'Subvention d''exploitation (les nouvelles recrues)', 'Recettes', null, null, null);
INSERT INTO public.configuration_rubrique_budgetaire_generale (id, archived, import_id, import_origin, version, created_on, updated_on, attrs, code_budg, name, type, created_by, updated_by, parent) VALUES (303, null, null, null, null, null, null, null, '7162', 'Subventions relative au Plan de développement', 'Recettes', null, null, null);
INSERT INTO public.configuration_rubrique_budgetaire_generale (id, archived, import_id, import_origin, version, created_on, updated_on, attrs, code_budg, name, type, created_by, updated_by, parent) VALUES (304, null, null, null, null, null, null, null, '718', 'Autres produits d''exploitation', 'Recettes', null, null, null);
INSERT INTO public.configuration_rubrique_budgetaire_generale (id, archived, import_id, import_origin, version, created_on, updated_on, attrs, code_budg, name, type, created_by, updated_by, parent) VALUES (305, null, null, null, null, null, null, null, '7513', 'Produits des cessions d''immobilisations corporelles', 'Recettes', null, null, null);
INSERT INTO public.configuration_rubrique_budgetaire_generale (id, archived, import_id, import_origin, version, created_on, updated_on, attrs, code_budg, name, type, created_by, updated_by, parent) VALUES (306, null, null, null, null, null, null, null, '758', 'Produits destiné au Centre multiservices Ain Chkef', 'Recettes', null, null, null);
INSERT INTO public.configuration_rubrique_budgetaire_generale (id, archived, import_id, import_origin, version, created_on, updated_on, attrs, code_budg, name, type, created_by, updated_by, parent) VALUES (307, null, null, null, null, null, null, null, '7531', 'Produits destiné à la construction du parc des expositions de Fès', 'Recettes', null, null, null);
INSERT INTO public.configuration_rubrique_budgetaire_generale (id, archived, import_id, import_origin, version, created_on, updated_on, attrs, code_budg, name, type, created_by, updated_by, parent) VALUES (308, null, null, null, null, null, null, null, '7532', 'Produits destiné à la construction du palais de la foire de taza', 'Recettes', null, null, null);
INSERT INTO public.configuration_rubrique_budgetaire_generale (id, archived, import_id, import_origin, version, created_on, updated_on, attrs, code_budg, name, type, created_by, updated_by, parent) VALUES (309, null, null, null, null, null, null, null, '760', 'Subvention du conseil de la région Fès Meknes pour la réalisation du SIG de la cartographie économique', 'Recettes', null, null, null);
